// <auto-generated />
using INF_01127.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace INF_01127.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20230716214148_V1")]
    partial class V1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("INF_01127.Models.Actors.DonorModel", b =>
                {
                    b.Property<int>("Identification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Identification");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identification"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.HasKey("Identification");

                    b.ToTable("Donors");
                });

            modelBuilder.Entity("INF_01127.Models.Actors.KitchenModel", b =>
                {
                    b.Property<int>("Identification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Identification");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identification"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Location");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<bool>("Validated")
                        .HasColumnType("bit")
                        .HasColumnName("Validated");

                    b.HasKey("Identification");

                    b.ToTable("Kitchens");
                });

            modelBuilder.Entity("INF_01127.Models.Actors.ManagerModel", b =>
                {
                    b.Property<int>("Identification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Identification");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identification"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("Name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.HasKey("Identification");

                    b.ToTable("Managers");
                });

            modelBuilder.Entity("INF_01127.Models.Actors.UserModel", b =>
                {
                    b.Property<int>("Identification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Identification");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Identification"));

                    b.Property<string>("EmailAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("EmailAddress");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Password");

                    b.Property<bool>("Type")
                        .HasColumnType("bit")
                        .HasColumnName("Type");

                    b.HasKey("Identification");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
